// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDugwrZP8HD3CdFnPndpPhAJwyVf85Y1iQ',
    appId: '1:254007085784:web:acc23e0d71fc754de4e5ad',
    messagingSenderId: '254007085784',
    projectId: 'portfolio-pro-debfd',
    authDomain: 'portfolio-pro-debfd.firebaseapp.com',
    storageBucket: 'portfolio-pro-debfd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj_q-xjfV9U7hwUAd_crQkov1zwEkdoNw',
    appId: '1:254007085784:android:d36967c584c42985e4e5ad',
    messagingSenderId: '254007085784',
    projectId: 'portfolio-pro-debfd',
    storageBucket: 'portfolio-pro-debfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ0NZqdmwTbnbxSjujcec488jTEfEpmw8',
    appId: '1:254007085784:ios:140f5c8e36ca79d5e4e5ad',
    messagingSenderId: '254007085784',
    projectId: 'portfolio-pro-debfd',
    storageBucket: 'portfolio-pro-debfd.firebasestorage.app',
    iosBundleId: 'com.example.portfolioPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ0NZqdmwTbnbxSjujcec488jTEfEpmw8',
    appId: '1:254007085784:ios:140f5c8e36ca79d5e4e5ad',
    messagingSenderId: '254007085784',
    projectId: 'portfolio-pro-debfd',
    storageBucket: 'portfolio-pro-debfd.firebasestorage.app',
    iosBundleId: 'com.example.portfolioPro',
  );
}
